# @format

version: "3"
services:
  app:
    container_name: express
    image: farbreaker/demonode:0.0.8
    ports:
      - "8081:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
